### PR TITLE
Issue#9 create listing Fix addEvent function w/ relationships b/w listing and user

### LINKED ISSUE #9: Backend: user can create event listing

### PR DESCRIPTION
**Pull request by Mxx1029**

### CODE REVIEW

File: controllers/userController.js [hunk 1]
```diff
@@ -1,55 +1,69 @@
...
 // Get a list of all users
 const getUsers = (req, res) => {
-    
-    // just for testing
-    res.json({ success: "ok" })
+	// just for testing
+	res.json({ success: "ok" });
 };
 
 const getUser = () => {};
```
Comment (mariagluck) [inline controllers/userController.js:10]: I guess you know that this is empty?

File: controllers/userController.js [hunk 2]
```diff
@@ -1,55 +1,69 @@
...
+        
+
+		res.json({ user, token });
+	} catch (error) {
+        next(error);
+    }
+};
 
 // Update a user
 const updateUser = () => {};
```
Comment (mariagluck) [inline controllers/userController.js:55]: Same here, I guess that would be next/last to work on, the update user...?

**Review by mariagluck — APPROVED** [review]
Great work!

File: controllers/userController.js (hunk 1 above)
Comment (Mxx1029) [reply controllers/userController.js:10]: yes, i know. it will probably stay empty, because there's no frontend functionality (this would be an admin dashboard, so only nice to have)

File: controllers/userController.js (hunk 2 above)
Comment (Mxx1029) [reply controllers/userController.js:55]: same here. no frontend side of this, and also not MVP.
